### ISSUE TITLE
Reset button emits rangeSelected with no start date

### ISSUE THREAD

**Issue by ryshep111** [alsoicode/ngx-daterange#1]
Think this should be just marking 'start' in IDateRange as potentially null

**Comment by alsoicode** [comment]
Hi Ryan. I'll take a look at this as quick as I can for you. Slammed on a prototype at work at the moment.

**Comment by ryshep111** [comment]
Yup no worries, should I think just be marking ```start: momentNs.Moment;``` as ```start?: momentNs.Moment;``` or ```start: momentNs.Moment | null;```

**Comment by alsoicode** [comment]
Should be fixed by: https://github.com/alsoicode/ngx-daterange/pull/2 I just removed the event emitter call entirely, so no data is emitted when .reset() is called.

1.0.8 is available on npm
