### ISSUE TITLE
FromDate - ToDate default date unable to reset with "Reset button"

### ISSUE THREAD

**Issue by Yorer** [alsoicode/ngx-daterange#12]
There is a problem when I give some prepopulated dates. It is setting the date, but after that, it can not  reset anymore, so the dates will be still there even if I press reset button.

To reproduce this bug just simply create a fromDate and toDate moment value, and try press the reset button. The value in the input field will be reset, but the daterange in the popup picker will be still showing the date, also unable to modify it manually by clicking on any date.

**Comment by alsoicode** [comment]
Well that's not good. Let me see if I can figure out what's going on.

**Comment by Yorer** [comment]
Thanks you very much alsoicode. Btw it's an awesome module if it will work I will be extremely happy because I would like to use it in a lot of places, and this date range selection is way better than the others.

**Comment by alsoicode** [comment]
@Yorer No problem at all, and thanks for the kind compliments.

I'm having some difficulty replicating the problem you're experiencing though, so I'm going to need a little more help.

Using the sample project the module is built around, I added a `[fromDate]` and `[toDate]` `moment` instance to a `<date-range-picker>` instance. After clicking the reset button, the values were cleared from the inputs as well as the calendars.

I'm using the latest version, 1.18.0, transpiled with Node 13.8.0.

What version are you using, and what browser are you seeing this problem in? Also are you dynamically instantiating the date-range-picker instance or any other special circumstances I may not have alowed for in testing?

Thanks,
Brandon

**Comment by alsoicode** [comment]
@Yorer I had actually not added a unit test for the reset functionality, but a quick one like this:

```
describe('Testing reset', () => {
    it('should clear the inputs as well as the calendar instances when .reset() is called', async(() => {
      const now = moment();
      const fromDate = now.subtract(1, 'month');

      component.fromDate = fromDate;
      component.toDate = now;

      fixture.detectChanges();

      const event = new Event('click');
      component.reset(event);

      expect(component.fromDate).toEqual(null);
      expect(component.toDate).toEqual(null);
      expect(component.range).toEqual('');

    }));
  });
```

is indicating that everything _should_ be working as expected. The calendar controls base their display on the `fromDate` and `toDate` values they receive from the `date-range-picker` instance. Unless something is stepping on the reset function, I'm not sure what might be going on.

**Comment by Yorer** [comment]
Is it working for you? I'll take a look at it tomorrow and I'll share some advanced informations with you. Thanks for take a look at it anyway. I'll reply soon.

**Comment by alsoicode** [comment]
Yes, in my manual and automated testing it's working as expected.

**Comment by Yorer** [comment]
Okay so I've pulled your project and modified the demo component. (app.component) I've got the same there as well: what I've did, I just modified the first date picker on the template file:

(fromDate, toDate)

`<date-range-picker #dateRangePicker [options]="firstFieldOptions" [fromDate]="getStartDate()" [toDate]="getEndDate()" [parentFormGroup]="form" [controlName]="'firstDateRange'" (rangeSelected)="onRangeSelected($event)"></date-range-picker>`

On the js file I've added 2 functions:
```
getStartDate(){
    return moment();
}

getEndDate(){
    return moment();
}
```

After that I've opened Date range picker popup and pressed "Reset". "Today" in the popup was still selected so the dom element, and the input field was empty. This is my exact issue, and it's a problem because as I know this is the only way to prepopulate daterange.

Ohh and I can't select anything else after I pre-select some fields

I'm using angular 9.0.1
NPM: 6.12.1
Node: 12.13.1
Moment: 2.24.0

**Comment by alsoicode** [comment]
OK, I see what the problem probably is. Setting the `[fromDate]` and `[toDate]` inputs from a function is going to cause those to get set many times unless you have change detection turned off.

It's never a good idea to call functions directly in template code unless you don't have any other choice, and if you don't, make sure you've set change detection to OnPush, or you're going to get a lot of side effects.

Can you please try setting the from/to dates as properties on your component and populating them that way? This way they should only get populated one time, when your component initializes.

You can set them in nearly the same way...

```
class YourComponent {

  startDate = moment();
  endDate = moment();

}
```

Thanks,
Brandon

**Comment by Yorer** [comment]
Ohh wow it did the trick!! Next time I will use more carefully functions in template. Thanks Brandon,
Adam

**Comment by alsoicode** [comment]
You're welcome. I though that was probably the case. After 4+ years of developing with Angular, the first thing I do with every component is turn change detection off and only invoke it when it's needed.

Or, if I'm being lazy or just working on something very quick, I make sure not to call functions in template code because they'll get called on every change detection cycle. In cases like this, you'd never want those functions to get called more than once, so it's best just to set the properties on the view model of the component, or set them in the OnInit.

Let me know if you run into any more issues though, I can only test so many scenarios.
