### ISSUE TITLE
Support for DayJS

### ISSUE THREAD

**Issue by dar097** [alsoicode/ngx-daterange#19]
I'd really like to try out your date range picker as it looks beautiful, but my project uses DayJS for date parsing. Most of the functionalities are the same as MomentJS, however I'm not sure you'd find a DayJS plugin equivalent to 'moment-range'. Thanks

**Comment by alsoicode** [comment]
Sorry for the late reply. ngx-daterange outputs the value for the date as a string, which you can parse however you need. This could be done after you get the form values and before you pass the value to other code.
