### ISSUE TITLE
Error-message when compiling in Angular 8

### ISSUE THREAD

**Issue by MrBasque** [alsoicode/ngx-daterange#22]
When using in Angular 8 gives the following error.
All seems te be working fine though.

`   
    ERROR in node_modules/ngx-daterange/components/calendar/calendar.component.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/ngx-daterange/components/datepicker/date-range-picker.component.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context.
    
`

![image](https://user-images.githubusercontent.com/1436027/81927558-212e8380-95e4-11ea-8439-f765734a8eaa.png)

**Comment by alsoicode** [comment]
I'll have to find some time to look into that. I'm sequestered on a covid project at work and have had zero extra time for weeks.

**Comment by alsoicode** [comment]
@MrBasque finally had some time to look into this.

I downgraded to Angular 8.3.28 and TypeScript 3.5.3, but I can't replicate this issue. The sample app will run correctly and the library will compile. Tests are also passing.

I made some changes to fix a couple of other issues that might have fixed the error in the date-range-picker component as a side effect, but so far, I haven't seen this issue pop up.

Please let me know if you're still having issues and I can re-open this.

**Comment by MrBasque** [comment]
We've upgraded to project to Angular 9 in the meantime, and also upgraded typescript to the latest version. 
No problems since then. Anyway, thank you for your effort!

**Comment by alsoicode** [comment]
@MrBasque Cool. I've recently made some changes to add better mobile styling and fix an issue on Safari. 1.0.25 is the latest version on NPM.
