### ISSUE TITLE
Not all days are showing in some Months

### ISSUE THREAD

**Issue by EdwardvanLieshout** [alsoicode/ngx-daterange#23]
Months where the days are spread out over 6 rows have the days in the last row cut off.
Examples: 

- January 2020 (31st is missing)
- January 2021 (30th and 31st are missing)
- May 2020 (31st is missing)
- May 2021 (30th and 31st are missing)

**Comment by alsoicode** [comment]
Well that's certainly a problem. I'll try to get that addressed as soon as I can. Thanks for letting me know.

**Comment by alsoicode** [comment]
OK, this has been fixed in 1.0.21, which is available in npm
