### ISSUE TITLE
Display Issues

### ISSUE THREAD

**Issue by ell360** [alsoicode/ngx-daterange#25]
Hiya, 

It's possible i'm being dumb... but any idea why the date picker is always displayed and why it's misaligned (see image, this is how it is on page load)? 

Feel like I've followed the setup instructions correctly but there's something i'm missing here.

Tested on an existing project and a freshly created one... Also worth noting that it does appear to work whilst, I can interact with it, the close button does nothing.

![date range issue](https://user-images.githubusercontent.com/58640377/85313219-c83def00-b4af-11ea-986e-9fcf82467e90.png)

**Comment by alsoicode** [comment]
Hi. ngx-daterange is dependent on Bootstrap 4+ for styling. Can you confirm you're using Bootstrap and it's being applied to your app?

**Comment by ell360** [comment]
That'll do it, i'm dumb! 
Amazing, thank you very much!

**Comment by alsoicode** [comment]
No worries at all. I should make that more clear in the readme.
