### ISSUE TITLE
Setting clickOutsideAllowed to true causes errors in Safari

### ISSUE THREAD

**Issue by EdwardvanLieshout** [alsoicode/ngx-daterange#26]
When setting the clickOutsideAllowed option to true, the datepicker stops working and throws an error whenever I try to open. This problem only was happening to me in Safari.

<img width="563" alt="image" src="https://user-images.githubusercontent.com/66299691/85997035-4b5bc980-ba09-11ea-870f-72dc3a81d841.png">

**Comment by alsoicode** [comment]
Thanks for the report. I'll try to look into this and your other issue as quickly as possible.

**Comment by alsoicode** [comment]
This has been fixed in version 1.0.22
