### ISSUE TITLE
Apply and close buttons do not show on the single calendar, even if autoApply is false

### ISSUE THREAD

**Issue by EdwardvanLieshout** [alsoicode/ngx-daterange#27]
Looks like the buttons are not added in when using a single calendar:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/66299691/85997949-7c88c980-ba0a-11ea-9601-f869cacc0d9e.png">

**Comment by alsoicode** [comment]
This has been fixed in version 1.0.23
