### ISSUE TITLE
Uncaught TypeError in 1.0.23 - prevents page from loading

### ISSUE THREAD

**Issue by EdwardvanLieshout** [alsoicode/ngx-daterange#33]
I tried changing around the options and switching browsers, but the same error still occurred.

![afbeelding](https://user-images.githubusercontent.com/66299691/86772660-b97d3d80-c054-11ea-8035-23b77b0fc633.png)

**Comment by alsoicode** [comment]
I'm going to need some more information to diagnose this. I've tested it on an Angular 9 / 10 project in Safari 13.1.1 and I'm not seeing this error.

**Comment by koreem** [comment]
<img width="1201" alt="Screenshot 2020-07-07 at 15 59 27" src="https://user-images.githubusercontent.com/6543690/86792555-e9374000-c06a-11ea-808c-6affe074fba7.png">
 
In Chrome.

**Comment by alsoicode** [comment]
What version of Angular are you using? also, what version of Node are you transpiling in?

For example, the sample project for ngx-daterange uses Angular 10 and compiles against Node 12.16.2

**Comment by koreem** [comment]
I just tried it in a new blank Angular app (version 9). When I added the NgxDateRangeModule to the AppModule it broke. I'm using node v12.16.1

**Comment by alsoicode** [comment]
Thanks @koreem. I was able to replicate that issue. I haven't run into that before, so I'm not sure what's going on yet.

**Comment by alsoicode** [comment]
@koreem There seems to be some issue with the Calendar component and the Ivy compiler.

I was able to get a sample project with the same specs to work by disabling Ivy in the tsconfig:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableIvy": false,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```

I know that's not ideal, but I'm out of time at the moment and will continue to try to find a solution for this.

**Comment by koreem** [comment]
Thanks for the fast reply. Disabling Ivy is not an option for us.

**Comment by alsoicode** [comment]
@koreem Nor for me. I have a current project that will need this library and Ivy, so I should have time to work on this today.

**Comment by alsoicode** [comment]
@koreem Can you please see if you're having the same issue with 1.0.32?
