### ISSUE TITLE
Daterange picker doesn't popup anymore immediately on focus, only on focus out from input field

### ISSUE THREAD

**Issue by Yorer** [alsoicode/ngx-daterange#35]
As I can see the demo is also updated to use the latest Angular 10. In the past date-range-picker has shown when user focused the field. But as I can see (also in your demo) date-range picker will appear only, if you focus out from the field. I don't know this is a bug or it has been developed straight like this, but the previous solution when you focused the field and picker apperared was better, but maybe it's just broken I have no clue. :)

**Comment by Yorer** [comment]
Additional info:
Node: 12.18.2
NPM: 6.14.5
Angular: 10.0.2
ngx-daterange: 1.0.24

Browser: Chrome 83.0.4103.116 (x64)

Same issue can be reproduce in your demo

**Comment by alsoicode** [comment]
@Yorer Hi. Sorry, I can't replicate this, given the same versions of browser, etc.

I have recently pushed some updates to improve mobile styling, but as far as I can test, everything is working ok. I will re-open if I get any more reports of this.
