### ISSUE TITLE
December date still missing in release 

### ISSUE THREAD

**Issue by abhijeetkabule** [alsoicode/ngx-daterange#47]
![1234567](https://user-images.githubusercontent.com/20876403/99400919-93727e80-290d-11eb-9d6d-0eb5ff1e71ce.PNG)

Dec-2019 -- still missing 29th dec

**Comment by alsoicode** [comment]
Fixed in 1.0.33. Version 1.0.34 is now the latest.

**Comment by abhijeetkabule** [comment]
Thanks for the fix @alsoicode.

**Comment by alsoicode** [comment]
You're very welcome.
