### ISSUE TITLE
The dates of different month within a selected range are not highlighted 

### ISSUE THREAD

**Issue by tusharj160** [alsoicode/ngx-daterange#48]
![image](https://user-images.githubusercontent.com/17896318/99639235-64731e80-2a6d-11eb-82b1-ae350f72551d.png)

**Comment by tusharj160** [comment]
Hi, thanks for the package I have been using this in my project and recently found this issue where the dates of the different months within the selected date range are not being highlighted.is this the expected behaviour of the plugin?

**Comment by alsoicode** [comment]
@tusharj160 I have refactored how the styling is applied for those dates and now you'll have both `in-selected-range` and  `different-month` applied for styling.

Release 1.0.34 is available on npm.

**Comment by tusharj160** [comment]
@alsoicode Thank you so much for the fix.

**Comment by alsoicode** [comment]
@tusharj160 You're very welcome. Thanks for bringing that to my attention.
