### ISSUE TITLE
December 2019 has a row of january 2019 

### ISSUE THREAD

**Issue by tusharj160** [alsoicode/ngx-daterange#50]
![image](https://user-images.githubusercontent.com/17896318/99786355-622fc380-2b44-11eb-949e-2998aef74a54.png)

The month of dec2019 has 5th row of january 2020 and 6th row of january 2019

**Comment by tusharj160** [comment]
This happens for all dec till 2022..As it is when the last date of the 5th row is Dec 31.

**Comment by alsoicode** [comment]
Yep, I see that. Very interesting. I'll take a look at that as soon as I can. Pull requests are always welcome.

**Comment by alsoicode** [comment]
@tusharj160 Can you please fork this project and run the `bugfix/next-year-has-incorrect-dates` branch to test?

I'm pretty sure I've corrected the issue, but would appreciate an extra set of eyes.

**Comment by tusharj160** [comment]
@alsoicode I forked the above branch and checked it. But the issue seems to be still there. I am also trying to fix this. I'll do a pull request if I find something.

**Comment by alsoicode** [comment]
Here's a screenshot of the date objects as rendered by the calendar component

![Screen Shot 2020-11-22 at 8 02 41 AM](https://user-images.githubusercontent.com/86738/99904511-396d1280-2c99-11eb-9756-d42e05d26a98.png)

each day is a Moment.js object. As shown by the data-day attribute, the days of the next year have the correct dates.

When selecting a day in the next or previous month, the calendar will jump to the month for the day, but the date selected is correct. I manually advanced back through the months to the "From" date, and no previous days were selected on the way.

**Comment by alsoicode** [comment]
@tusharj160 I'm going to go ahead and merge this fix. If there's anything else you discover, I'll get it worked in.

**Comment by tusharj160** [comment]
@alsoicode i agree with data-day attribute are of the next year but if you see the 6th row of dec 2019 it starts with date 6(which is from january 2019 instead january 2020) and missing the dates from 5th of january 2020

**Comment by alsoicode** [comment]
Well son of a bitch. I thought I had fixed that in an earlier release. Ugh!

**Comment by alsoicode** [comment]
@tusharj160 OK, this has been fixed in 1.0.36

**Comment by tusharj160** [comment]
@alsoicode great, working fine now. Thanks for the quick resolution.
